name: Release MSPP4

on:
  push:
    branches: [ main , develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v8
      with:
        path: artifacts

    - name: List downloaded artifacts
      run: |
        find artifacts -type f -name "*" | sort

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: true
        # ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
        generate_release_notes: true
        files: |
          artifacts/mspp4-installer-windows/*
          artifacts/mspp4-installer-macos/*
          artifacts/mspp4-installer-macos-intel/*
          artifacts/mspp4-installer-linux-debian/*
          artifacts/mspp4-installer-linux-rpm-alma9/*
          artifacts/mspp4-installer-linux-rpm-alma10/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

